version: '3'
services:
  web:
    image: yotamdavid/app_ferari:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db-service
    restart: always
  db-service:
    image: yotamdavid/appdatabase:latest
    container_name: mysql-service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yotam
      MYSQL_DATABASE: users
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  db-data:
